name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']

# Add concurrency control
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Cache build
        uses: actions/cache@v4
        with:
          path: |
            build
          key: ${{ runner.os }}-svelte-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-svelte-

      - name: Install dependencies
        run: npm install

      - name: Build
        env:
          BASE_PATH: '/nextseq-sample-sheet-validator'
        run: |
          npm run build
          touch build/.nojekyll

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4